language: python
dist: xenial
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - LANG=en_US.UTF-8
matrix:
  include:
    - env:
        - TOXENV=py38,codecov
      python: '3.8'
install:
  - pip install -U tox-travis
  - pip install -r dependencies/requirements_dev.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script: tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
after_success:
  - codecov
notifications:
  email: false
